%module(directors="1", moduleimport="# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import libDiagnosticsService
else:
    import libDiagnosticsService") DiagnosticsService

%feature("director") platform::diagnostics::GeneralDiagnosticsServiceClient;

%begin %{
#define SWIG_PYTHON_2_UNICODE
%}

%include <std_vector.i>
%include <std_string.i>
%include <std_shared_ptr.i>
%include <std_unordered_map.i>
%include <std_unordered_set.i>

%include "../swig-patch/Common-patch.i"
%include "../swig-patch/TDeferredResponse-patch.i"

%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AMGRaceAppConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/NotAvailableAvailable.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/FilterFactor.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/ExceptionsService/inc/OperationNotSupported.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ActivateSARDataStorageConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SARStorageStatus.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ActivatedDeactivated.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ActiveComfortConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/NotInstalledInstalled.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OffOn.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ACAnimations.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PowernapDuration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DisabledEnabled.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ACInteger.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ProgramDurationType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PowerNapDurationFront.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PowerNapDurationRear.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AddressBookConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/InitialNamePresentationType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/InitialPhonebookDownloadMode.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VCharSets.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AirconditionConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AirconZonesV1.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AirconFrontZones.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PreconTypes.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CodingSource.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AmbientLightConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AmbientLightType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ALTimeToFade.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ALFadingTime.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AntennaConfigurationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCNAntennaConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCNBandType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DelayTime.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AssistanceAtBreakdownOrAccidentConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCN_ABACountry.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCNWarningTriangle.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCNFirstAidKit.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AssistanceConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AudioHandlingConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SoundLogoType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AugmentedRealityConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ARCParameterV2.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ARCParameter.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DashcamSpeedFormat.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PoseMasterType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/RearAxleSteeringType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AutoAROnHighway.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/BluetoothConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/BrowserConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MobiWebsiteURLNew.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CANTelematicComponentsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TRUE_FALSE.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MMBoxType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/NumberOfCharger.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/Car2XConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CarDataVisualizationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CarDataVisualizationObjectLayer.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AnalogueUnitsScreenSwitch.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/GForceAccMaxVal.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/IndicationBrakeTorqueGainFactor.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AnalogueInstrumentTorqueScaleValueType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AnalogueInstrumentPowerScaleValueType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleLevelPositionM1RelativeReference.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleLevelPositionP0RelativeReference.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleLevelPositionP1RelativeReference.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleLevelPositionP2RelativeReference.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleLevelPositionP3RelativeReference.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleLevelPositionM2RelativeReference.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/GForceLStretchFactor.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleWheelPlungerDataSourceSignal.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/EngineBoostPressure.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleSpeedDivisorType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/GForceParameterK.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OSReceiveBufferSize.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OSDisplayBufferSize.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OSDisplayBufferUpdateTime.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OSRankingMaximumDataLines.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OSHistoryMaximumDataLines.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CarSharingConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CodingDependentDTCsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CompanionAppConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DRCAMConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DigitalOwnersManualConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MountPointDOM.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DOMContentString.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DriveProgramDataMatrixConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgram.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DriveProgramHMIUsageOrder.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SpeedThreshold.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SpeedHysteresis.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/FalseTrue.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DriveProgramsIndividualSettingsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DriveProgramsSettingsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramSelectionSwitchType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramIndicationTimeout.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramIndicationTimeoutOffset.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramOperationTimeoutDSS.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramDropTimeout.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramFaultTimeout.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramRecoveryRequestAnswerFocus.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrvProgTimerType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrvProgSpeedType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivingProgramSLMaxEntries.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ESSConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TuningVariantType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/EnergyFlowConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/EnergyFlowConsumptionUnit.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ConsumptionScaleMax.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/EnergyFlowGallonType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DrivenWheels.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/EnergyFlowDriveType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ConsumptionFactor.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TimeRangeScheme.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/FeedbackManagerConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/BufferLength.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/FondTelefonieSettingsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ActiveInactive.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/InstalledNotInstalled.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OnOff.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/HDMapDataCollectorConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DCLoggingHU.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DCLoggingDaiVB.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/HSDLTelematicComponentsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ICCodingConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ICGeneration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ICVariant.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ICVehicleLineYear.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ICIndexWithinVLY.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/InCarCommunicationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/InternetConnectivityConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/BackendType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OperatingModeTEL_ECU.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/KeepaliveFailedProbes.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/KeepaliveTime.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TriggerWiFiHotspotSearch.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ExternalWiFiHotspotMode.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DeactivatedActivated.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LunarDateConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MBECallConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MOSTTelematicComponentsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SoundTypeV2.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MainConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/Language.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/StyleguideSafeMode.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CIScreenTypes.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/NoYes.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DisplayTouchTypes.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/StyleguideTypes.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VANBodyStyleTypes.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OSPType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SystemLanguageSets.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LoggingModeType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MaxHSDLConfigurationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/HSDL_ID.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MaxMostConfigurationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MOST_DIAG_ID.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MessagingConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/InitialMsgDownload.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MultifunctionalSeatConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PulseModes.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/NavigationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ADASSupport.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/HOVLaneSupport.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CompassType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TrafficFlowColoringSchemeType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/NavigationRegion.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MB_POIDatabase.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TankRangeType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/MapVersionMarket.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/NaviSearchEngine.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/GNSSConfigurationType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LanePosAcousGuidCA.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LanePosAcousGuidNoCA.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LanePosVisGuidCA.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LanePosVisGuidNoCA.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/EVRangeAssistantType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LanePosSrc.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PMASign.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PMAM100thDigit.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PMAM10thDigit.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PMAM1thDigit.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SearchEngineType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OnOffBehaviourConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/UserOffStyleType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ParkingSupportConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/CameraType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DisplayType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PixelHDImageConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PHDResendCounter.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PHDResendOffset.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PlayerConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/RSETypeV2.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PushNotificationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/RemoteTelematicsSoftwareUpdateConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/RemoteUISettingsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/RestrictedFunctionsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/RestrictionType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VideoRestrictionType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SDARSPackageIndexConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PackageIndex.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ServiceCallConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ServiceCallCounter.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SpecialPurposeVehiclesConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SPVIconType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SpeechDialogSystemConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SystemActivationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SystemPINConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TVCountrySettingConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCN_TVCountry.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TV_ESNIndexConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SupportByECUType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ProductionCardTestType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/UnusedDataType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TactileTouchscreenConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/HapticFeedbackTSC.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/OperationMode.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ForceSensitivity.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TelelogConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TelelogUserCategory.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TelelogConfigSource.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TelephoneConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TimeAndDateConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/DateFormat.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TimeFormat.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TrafficConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TrafficFlowStateBasisType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TrafficRegion.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ColoringScheme.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TunerApplicationConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/FrequencyTable.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/AM_FMRangeType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TPEGProviderType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TuningParameterConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TuningParameter.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/UICMConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/UserActionPredictionConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/UserDataConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/UDXSettings.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VANConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VehicleFunctionsConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/EasyEntryExitType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TowawayIntSensorType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/RoofStyle.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ILSTrafficStyle.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/BlindSpotDataType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LDPType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TSAType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/TireSpeedLimitVariantType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ESPCRocking.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ESPCLowLevel.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SmartChargeVal.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LaneChangeAssistantType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PanelHeating.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SundBlindStyleType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LocBasedChargDistHome.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/LocBasedChargDistWork.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ChargingProgVersion.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VideoHandlingConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCNDisplayResolutionV3.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCNPiPResolutionV3.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCNAssistSystemResV2.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/SCNCoDriverDisplayResolutionV2.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ParkPilotVariantType.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/VitalityCoachConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ClearTime.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ResumeRecommendationTime.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/HRValueStoreTime.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/StressCycle.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/StressAnalyzedTime.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/WLANGatewayConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/WirelessPowerTransmissionConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/WirelessSubsystemConfiguration.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/WLANAntenna.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/WLANCountryCodeV2.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/PrefixInfotainmentName.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/ConfigurationInvalidException.h"

%include "../../../../SourceSpace/ThriftMe/ThriftMe/inc/platform/CompilerFeatures.h"
%include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/GeneralDiagnosticsService.h"

%{
#include "../../../../SourceSpace/IF1ThriftMeFull/DiagnosticsService/inc/GeneralDiagnosticsService.h"
%}

%inline %{
platform::diagnostics::GeneralDiagnosticsServiceClient*
GeneralDiagnosticsServiceClient_createSimpleClient(std::string address) 
{
    ::thrift::TServiceBrokerConfigurationBuilder builder;
    ::thrift::shared_ptr< ::thrift::TServiceBroker > broker(new ::thrift::TServiceBroker(builder.build()));

    ::thrift::shared_ptr< platform::diagnostics::GeneralDiagnosticsServiceClient > client = platform::diagnostics::GeneralDiagnosticsServiceClient::createClient(broker, address);

    ::thrift::shared_ptr< platform::diagnostics::GeneralDiagnosticsServiceClient > shared_ptr_eraser(nullptr, 
        [](platform::diagnostics::GeneralDiagnosticsServiceClient *pi) { 
            // custom smart pointer deleter
            // do not delete object
            // since we will move the pointer to Python environment
        });

    shared_ptr_eraser = std::move(client);

    return shared_ptr_eraser.get();
}

void GeneralDiagnosticsServiceClient_waitForConnection(platform::diagnostics::GeneralDiagnosticsServiceClient *self)
{
    self->getTransport()->waitForConnection();
}
%}

%pythoncode %{
@staticmethod
def static_GeneralDiagnosticsServiceClient_createSimpleClient(address):
    return libDiagnosticsService.GeneralDiagnosticsServiceClient_createSimpleClient(address)
GeneralDiagnosticsServiceClient.createClient = static_GeneralDiagnosticsServiceClient_createSimpleClient

def GeneralDiagnosticsServiceClient_waitForConnection(self):
    return libDiagnosticsService.GeneralDiagnosticsServiceClient_waitForConnection(self)
GeneralDiagnosticsServiceClient.waitForConnection = GeneralDiagnosticsServiceClient_waitForConnection
%}
